import input from '@inquirer/input';
import * as fs from 'fs';
import { logger } from '../logger';
import path from 'path';
import { packageJson } from '../utils';

export async function init() {
  let entryPoints: string;
  let cssPath: string;
  let instancePath: string;

  logger.announcement();

  try {
    entryPoints = await input({
      message: 'Where is your code?',
      default: './src/**/*.{ts,tsx,js,jsx}',
    });

    cssPath = await input({
      message: 'Where do you want to place the extracted CSS?',
      default: './src/styles/morfeo.css',
    });

    instancePath = await input({
      message: 'Where do you want to create the morfeo instance?',
      default: './src/morfeo.ts',
    });

    logger.whitespace();
  } catch {
    logger.warning('Aborted by user.');

    return process.exit(0);
  }

  await Promise.all([
    writeCssFile(cssPath),
    writeInstanceFile({
      cssPath: getRelativePath(instancePath, cssPath),
      entryPoints: getRelativePath(instancePath, entryPoints),
      instancePath,
    }),
    writeToGitIgnore(['# morfeo', cssPath]),
  ]);

  logger.success('Morfeo has been initialized');
}

async function writeCssFile(targetPath: string) {
  try {
    await fs.promises.writeFile(
      path.join(process.cwd(), targetPath),
      '/* This file will be auto-generated by morfeo */',
    );

    logger.success(`CSS file created at ${targetPath}`);
  } catch {
    logger.error(`Error while creating CSS file at ${targetPath}`);
  }
}

async function writeInstanceFile({
  cssPath,
  entryPoints,
  instancePath,
}: {
  cssPath: string;
  entryPoints: string;
  instancePath: string;
}) {
  try {
    await fs.promises.writeFile(
      path.join(process.cwd(), instancePath),
      `import { createMorfeo } from '@morfeo/${
        isReactCodebase() ? 'react' : 'web'
      }';
  
export const morfeo = createMorfeo({
  entryPoints: ['${entryPoints}'],
  output: '${cssPath}'
});
`,
    );

    logger.success(`Morfeo instance file created at ${instancePath}`);
  } catch {
    logger.error(
      `Error while creating morfeo instance file at ${instancePath}`,
    );
  }
}

async function writeToGitIgnore(lines: string[]) {
  try {
    const gitIgnorePath = path.join(process.cwd(), '.gitignore');

    const gitIgnoreContent = await fs.promises.readFile(gitIgnorePath, {
      encoding: 'utf-8',
    });

    if (gitIgnoreContent.includes('# morfeo')) {
      logger.warning(`Morfeo CSS file seems already gitignored`);

      return;
    }

    await fs.promises.writeFile(
      gitIgnorePath,
      `${gitIgnoreContent}\n${lines
        .map(line => `${line[0] === '.' ? '' : '.'}${line.slice(1)}`)
        .join('\n')}`,
    );

    logger.success(`Added morfeo CSS file to .gitignore`);
  } catch {
    logger.error(`Error while gitignoring morfeo files`);
  }
}

function isReactCodebase() {
  return (
    'react' in (packageJson.dependencies ?? {}) ||
    'react' in (packageJson.peerDependencies ?? {})
  );
}

function getRelativePath(fromPath: string, toPath: string) {
  const relativePath = path.relative(path.dirname(fromPath), toPath);
  return relativePath.startsWith('./') ? relativePath : `./${relativePath}`;
}
