name: Build Morfeo

description: Common action in all the Morfeo workflows, it checks out and sets up the environment.

runs:
  using: 'composite'

  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
