name: Build Morfeo

description: Common action in all the Morfeo workflows, it sets up the environment.

runs:
  using: 'composite'

  steps:
    - uses: pnpm/action-setup@v2.0.1

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
