export const colorsMap = [
  'bg',
  'fill',
  'color',
  'stroke',
  'caretColor',
  'accentColor',
  'borderColor',
  'outlineColor',
  'borderTopColor',
  'backgroundColor',
  'columnRuleColor',
  'borderLeftColor',
  'borderRightColor',
  'borderBottomColor',
] as const;
