export const radiiMap = [
  'borderRadius',
  'borderEndEndRadius',
  'borderTopLeftRadius',
  'borderEndStartRadius',
  'borderTopRightRadius',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'corner',
  'cornerEndEnd',
  'cornerTopLeft',
  'cornerEndStart',
  'cornerTopRight',
  'cornerStartEnd',
  'cornerStartStart',
  'cornerBottomLeft',
  'cornerBottomRight',
] as const;
