export const sizesMap = [
  'size',
  'width',
  'height',
  'minWidth',
  'maxWidth',
  'minHeight',
  'maxHeight',
  'flexBasis',
  'blockSize',
  'inlineSize',
  'maxBlockSize',
  'minBlockSize',
  'minInlineSize',
  'maxInlineSize',
] as const;
