export const gradients = {
  primary: {
    colors: ['gradient/start', 'gradient/middle', 'gradient/end'],
    start: { x: 1, y: 0 },
    end: { x: 0, y: 1 },
    useAngle: true,
    angle: 275,
    locations: [0.1, 0.6, 1],
    angleCenter: { x: 0.6, y: 0 },
  },
  secondary: {
    colors: ['gradient/end', 'gradient/middle', 'gradient/start'],
    start: { x: 0.75, y: 0.25 },
    end: { x: 0.25, y: 0.75 },
    useAngle: true,
    angle: 275,
    locations: [0, 0.5, 1],
    angleCenter: { x: 0.5, y: 0 },
  },
  success: {
    colors: ['success', 'primary'],
    start: { x: 1, y: 0 },
    end: { x: 1, y: 0 },
    useAngle: true,
    angle: 150,
    locations: [0, 0.75],
    angleCenter: { x: 0.8, y: 0.6 },
  },
  failure: {
    colors: ['error', 'warning'],
    start: { x: 1, y: 0 },
    end: { x: 1, y: 0 },
    useAngle: true,
    angle: 150,
    locations: [0, 0.75],
    angleCenter: { x: 0.8, y: 0.6 },
  },
};
