name: Build Web Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-web-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-environment

      - name: Install dependencies
        run: pnpm install

      - name: Build Web Extension
        run: pnpm build:web-extension
