name: Build Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-environment

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm build:docs
