name: Build Web Extension

on:
  pull_request:
    branches:
      - main

jobs:
  build-web-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ./.github/actions/setup-environment

      - name: Build Web Extension
        run: pnpm build:web-extension
