name: Deploy Web Extension

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  deploy-web-extension:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-environment

      - name: Install dependencies
        run: pnpm install

      - name: Build Web Extension
        run: pnpm build:web-extension

      - name: Deploy Web Extension
        run: pnpm deploy:web-extension
        env:
          WEB_EXTENSION_ID: ${{ secrets.WEB_EXTENSION_ID }}
          CHROME_WEB_CLIENT_ID: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          CHROME_WEB_REFRESH_TOKEN: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          CHROME_WEB_CLIENT_SECRET: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
